# Generated by Django 5.0.3 on 2024-06-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userdetails_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='text',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='cmtlikes', to='chat.userdetails')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmtposts', to='chat.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmtuser', to='chat.userdetails')),
            ],
        ),
    ]
