# Generated by Django 5.0.3 on 2024-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessages_title_alter_chatmessages_text_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='title',
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
