# Generated by Django 5.0.3 on 2024-06-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessages_title_posts_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='caption',
            new_name='title',
        ),
    ]
