# Generated by Django 5.0.3 on 2024-06-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_caption_posts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='chat/statics/groupicons')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=400)),
                ('admins', models.ManyToManyField(related_name='admins', to='chat.userdetails')),
                ('members', models.ManyToManyField(related_name='members', to='chat.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/statics/messages')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwriter', to='chat.userdetails')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups')),
            ],
        ),
    ]
