# Generated by Django 5.0.3 on 2024-07-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groups_groupmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.userdetails'),
        ),
    ]
