# Generated by Django 5.0.3 on 2024-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_groups_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='msgtype',
            field=models.CharField(default='message', max_length=10),
        ),
    ]
