# Generated by Django 5.0.3 on 2024-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_posts_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
